intro:
title: Deep Reinforcement Learning at the Edge of the Statistical Precipice
description: Oral at Neural Information Processing Systems (NeurIPS) 2021
buttons:
  Paper: 'https://arxiv.org/abs/2108.13264'
  Library: 'https://github.com/google-research/rliable'
  Colab: 'https://colab.sandbox.google.com/drive/1a0pSD-1tWhMmeJeeoyZM1A-HCW3yf1xR?usp=sharing'
  Tweetprint: 'https://twitter.com/agarwl_/status/1432800830621687817?s=20'
  Poster: 'pdfs/precipice_poster.pdf'
  Authors: '#authors'
