intro:
title: 'Beyond Tabula Rasa: Reincarnating Reinforcement Learning'
description: 'Neural Information Processing Systems'
'Oral at ICML 2022 Updatable ML Workshop'
buttons:
  Paper: 'https://arxiv.org/pdf/2206.01626.pdf'
  Code: 'https://github.com/google-research/reincarnating_rl'
  Slides: 'assets/slides_ttic.pdf'
  Authors: '#authors'

theme: jekyll-theme-cayman
