intro:
title: 'Reincarnating Reinforcement Learning: Reusing Prior Computation to Accelerate Progress'
description: 
- 'Neural Information Processing Systems (NeurIPS) 2022'
- 'Oral at ICML 2022 Updatable ML Workshop'
buttons:
  Paper: 'https://arxiv.org/pdf/2206.01626.pdf'
  Code: 'https://github.com/google-research/reincarnating_rl'
  Colab: 'https://colab.research.google.com/drive/1ktlNni_vwFpFtCgUez-RHW0OdGc2U_Wv?usp=sharing'
  Tweetprint: 'https://twitter.com/agarwl_/status/1577744273314922501?s=20&t=bCrK5tWVuLVO0cdEivMMVg'
  Slides: 'assets/reincaranting_rl_slides.pdf'
  Blog: 'https://ai.googleblog.com/2022/11/beyond-tabula-rasa-reincarnating.html'
  OpenReview: 'https://openreview.net/forum?id=t3X5yMI_4G2'
  Authors: '#authors'

theme: jekyll-theme-cayman
