intro:
title: Deep RL at the Edge of the Statistical Precipice
description: 
 - Outstanding Paper Award (Top 6/9122 submissions) at NeurIPS 2021
buttons:
  Paper: 'https://openreview.net/forum?id=uqv8-U4lKBe'
  Library: 'https://github.com/google-research/rliable'
  Colab: 'https://colab.sandbox.google.com/drive/1a0pSD-1tWhMmeJeeoyZM1A-HCW3yf1xR?usp=sharing'
  Tweetprint: 'https://twitter.com/agarwl_/status/1432800830621687817?s=20'
  Google AI Blog: 'https://ai.googleblog.com/2021/11/rliable-towards-reliable-evaluation.html'
  Blog: 'https://araffin.github.io/post/rliable/'
  Poster: 'pdfs/precipice_poster.pdf'
  Slides: 'assets/slides_mlc.pdf'
  Authors: '#authors'
 
